'use strict';

var formularioInicio;
var campoNombre;
var campoNivel;
var mensajeErrorInicio;
var pantallaInicio;
var pantallaJuego;
var tableroElemento;
var botonModoProgresivo;
var botonReiniciar;
var botonVolverInicio;
var marcadorNivel;
var marcadorIntentos;
var marcadorPares;
var marcadorErrores;
var marcadorPuntaje;
var marcadorTiempo;
var modalVictoria;
var modalContenidoVictoria;
var resultadoNombre;
var resultadoNivel;
var resultadoIntentos;
var resultadoErrores;
var resultadoTiempo;
var resultadoPuntaje;
var desglosePares;
var desgloseBonusRacha;
var desglosePenalizacionErrores;
var desgloseBonusRapidez;
var desgloseBonusIntentos;
var desgloseBonusFinalizar;
var desglosePenalizacionTiempo;
var botonJugarDeNuevo;
var botonCerrarModal;
var modalNivelCompletado;
var modalContenidoNivelCompletado;
var nivelCompletadoNombre;
var nivelCompletadoPuntaje;
var botonSiguienteNivel;
var modalResultadoProgresivo;
var modalContenidoResultadoProgresivo;
var resultadoProgresivoNombre;
var resultadoProgresivoIntentos;
var resultadoProgresivoErrores;
var resultadoProgresivoTiempo;
var resultadoProgresivoPuntaje;
var botonJugarDeNuevoProgresivo;
var botonCerrarResultadoProgresivo;

function iniciarAplicacion() {
    formularioInicio = document.getElementById('formulario-inicio');
    campoNombre = document.getElementById('nombre-jugador');
    campoNivel = document.getElementById('nivel');
    mensajeErrorInicio = document.getElementById('error-inicio');
    pantallaInicio = document.getElementById('pantalla-inicio');
    pantallaJuego = document.getElementById('pantalla-juego');
    tableroElemento = document.getElementById('tablero');
    botonModoProgresivo = document.getElementById('boton-modo-progresivo');
    botonReiniciar = document.getElementById('boton-reiniciar');
    botonVolverInicio = document.getElementById('boton-volver-inicio');
    marcadorNivel = document.getElementById('marcador-nivel');
    marcadorIntentos = document.getElementById('marcador-intentos');
    marcadorPares = document.getElementById('marcador-pares');
    marcadorErrores = document.getElementById('marcador-errores');
    marcadorPuntaje = document.getElementById('marcador-puntaje');
    marcadorTiempo = document.getElementById('marcador-tiempo');
    modalVictoria = document.getElementById('modal-victoria');
    modalContenidoVictoria = document.getElementById('modal-contenido-victoria');
    resultadoNombre = document.getElementById('resultado-nombre');
    resultadoNivel = document.getElementById('resultado-nivel');
    resultadoIntentos = document.getElementById('resultado-intentos');
    resultadoErrores = document.getElementById('resultado-errores');
    resultadoTiempo = document.getElementById('resultado-tiempo');
    resultadoPuntaje = document.getElementById('resultado-puntaje');
    desglosePares = document.getElementById('desglose-pares');
    desgloseBonusRacha = document.getElementById('desglose-bonus-racha');
    desglosePenalizacionErrores = document.getElementById('desglose-penalizacion-errores');
    desgloseBonusRapidez = document.getElementById('desglose-bonus-rapidez');
    desgloseBonusIntentos = document.getElementById('desglose-bonus-intentos');
    desgloseBonusFinalizar = document.getElementById('desglose-bonus-finalizar');
    desglosePenalizacionTiempo = document.getElementById('desglose-penalizacion-tiempo');
    botonJugarDeNuevo = document.getElementById('boton-jugar-de-nuevo');
    botonCerrarModal = document.getElementById('boton-cerrar-modal');
    modalNivelCompletado = document.getElementById('modal-nivel-completado');
    modalContenidoNivelCompletado = document.getElementById('modal-contenido-nivel-completado');
    nivelCompletadoNombre = document.getElementById('nivel-completado-nombre');
    nivelCompletadoPuntaje = document.getElementById('nivel-completado-puntaje');
    botonSiguienteNivel = document.getElementById('boton-siguiente-nivel');
    modalResultadoProgresivo = document.getElementById('modal-resultado-progresivo');
    modalContenidoResultadoProgresivo = document.getElementById('modal-contenido-resultado-progresivo');
    resultadoProgresivoNombre = document.getElementById('resultado-progresivo-nombre');
    resultadoProgresivoIntentos = document.getElementById('resultado-progresivo-intentos');
    resultadoProgresivoErrores = document.getElementById('resultado-progresivo-errores');
    resultadoProgresivoTiempo = document.getElementById('resultado-progresivo-tiempo');
    resultadoProgresivoPuntaje = document.getElementById('resultado-progresivo-puntaje');
    botonJugarDeNuevoProgresivo = document.getElementById('boton-jugar-de-nuevo-progresivo');
    botonCerrarResultadoProgresivo = document.getElementById('boton-cerrar-resultado-progresivo');
    registrarEventos();
    iniciarRanking();
    iniciarTema();
    iniciarSonidos();
}

iniciarAplicacion();
